module hw;

import base;

type DisplayMode =
{
    Size width,
    Size height,
    Size pitch
    Size format,
};

interface Display
{
    method modes -> DisplayMode[];
    method switch DisplayMode -> Bool;
    method surface -> IpcFb;
};
