module hw;

import base, math;

type DisplayMode =
{
    Size width,
    Size height,
    Size pitch
    Size format,
};

interface Display
{
    method current -> DisplayMode;
    method buffer -> IpcHnd;
};
