module pci;

import base;

type Identifier =
{
    U16 vendor,
    U8 class,
    U8 subclass,
};

type BarType = enum
{
    INVALID,
    BAR_MMIO_32,
    BAR_MMIO_64,
    BAR_PIO,
};

type Addr =
{
    U16 seg,
    U8 bus,
    U8 slot,
    U8 func,
};

type BarInfo =
{
    U64 base,
    U32 size,
    BarType type,
};

errors
{
    NOT_FOUND,
    INVALID_ADDR,
    NO_IRQ_FOR_DEVICE,
    IRQ_ALREADY_ENABLED
};

interface Server
{
    method query Identifier -> Addr;

    method bar { Addr addr, U8 num } -> BarInfo;

    method enable_irq { Addr addr } -> U8;
}
