module window;

import base, math, event, ui;

type WindowClientProps =
{
    MRectf bound,
    UiWinType type,
};

interface Client
{
    method show -> Bool;

    method hide -> Bool;

    method close -> Bool;

    method flip MRectf -> Bool;

    method move MRectf -> Bool;

    method surface -> IpcFb;

    method listen IpcCap -> Bool;
};

interface Server
{
    method create WindowClientProps -> IpcCap;
};
