module wm;

import base, math;



interface Client
{
    method resize MRect -> Nil;
    method flip MRect -> Bool;
    method close -> Bool;
};

interface Server
{
    method connect { MRect bound } -> IpcCap;
};


