module wm;

import base, math;

interface client
{
};

interface server
{
    method create_window { MRect bound } -> IpcCap;
};

interface window
{
    method resize MRect -> Nil;
    method flip MRect -> Bool;
    method destroy -> Bool;
};
