module wm;

import base, math, event, ui;

type WmClientProps =
{
    MRect bound,
    UiWinType type,
    UiWinFlags flags,
};

type WmLayout = enum
{
    WM_LAYOUT_STACK,
    WM_LAYOUT_FIBONACCI,
    WM_LAYOUT_MONOCLE,
} ;

interface Client
{
    method show -> Bool;

    method hide -> Bool;

    method close -> Bool;

    method flip MRect -> Bool;

    method move MRect -> Bool;

    method surface -> IpcFb;

    method listen IpcCap -> Bool;
};

interface Server
{
    method create WmClientProps -> IpcCap;
};
