#pragma once

// This is file is auto generated by BID, don't edit it!

#include <syscalls/types.h>

typedef enum {
example_PC_LOAD_LETTER,
} exampleError;

/* --- Types ---------------------------------------------------------------- */

typedef uint64_t exampleTime;

typedef struct {
exampleTime time;
} examplePingPong;

/* --- Messages ------------------------------------------------------------- */

typedef examplePingPong examplepingRequest;

typedef examplePingPong examplepingResponse;

typedef struct {
int foo;
} exampletestRequest;

typedef struct {
float bar;
} exampletestResponse;

typedef struct {
enum {
example_FOO,
example_BAR,
} type;
struct {
int data;
} nested;
} examplenotificationEvent;

typedef enum {
example_INVALID,
example_ERROR,
example_ping_REQUEST,
example_ping_RESPONSE,
example_test_REQUEST,
example_test_RESPONSE,
example_notification_EVENT,
} exampleMessageType;

typedef struct {
BrMessageHeader header;
union {
exampleError error;
examplenotificationEvent notification_event;
examplepingRequest ping_request;
examplepingResponse ping_response;
exampletestRequest test_request;
exampletestResponse test_response;
};
} exampleMessage;
